# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-13 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20180413_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='blogs_feed',
            field=models.ManyToManyField(blank=True, related_name='blogs_feed', to=settings.AUTH_USER_MODEL),
        ),
    ]
